// GMAI/server/models/GameState.js

const mongoose = require('mongoose');


const GameStateSchema = new mongoose.Schema({
    gameId: {
        type: String,
        required: true,
    },

    ownerUserId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        default: null,
    },
    memberUserIds: {
        type: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
        default: [],
    },
    /** Opaque single-use token for POST /api/auth/join; cleared after the first successful new-member join. */
    inviteToken: {
        type: String,
        select: false,
        default: null,
    },
    inviteTokenCreatedAt: {
        type: Date,
        default: null,
    },

    gameSetup: Object,
    conversation: Array,
    summaryConversation: Array,
    summary: String,
    summaryUpdatedAt: { type: String },
    // Baselines for when we last generated `summary` (used to throttle background summaries)
    summaryLastRunAtExchangeCount: { type: Number, default: 0 },
    summaryLastRunTokenApprox: { type: Number, default: 0 },
    totalTokenCount: Number,
    userAndAssistantMessageCount: Number,
    systemMessageContentDM: String,
    // mode: exploration | combat | investigation | decision | initial
    mode: {
        type: String,
        default: 'exploration',
    },
    // Structured campaign specification generated by campaign generator
    campaignSpec: {
        type: Object,
    },
    // Last combat / encounter snapshot from DM envelope (optional; not shown in narration)
    encounterState: {
        type: Object,
    },
    // Raw last AI model output (for debugging / audit). Stored server-side only.
    rawModelOutput: {
        type: String,
        select: false,
    },
    // Optional stored system-core prompt text (debug/audit; routes compose from prompt files at runtime)
    systemCore: {
        type: String,
        select: false,
    },
    // Raw last AI model REQUEST (system+user messages) for debugging. Stored server-side only.
    rawModelRequest: {
        type: String,
        select: false,
    },
    // LLM diagnostics and fallback metadata (timestamps and errors)
    llmCallEnteredAt: { type: String },
    llmCallStartedAt: { type: String },
    llmCallCompletedAt: { type: String },
    llmCallError: { type: String, select: false },
    llmCallFallbackAt: { type: String },
    llmFallbackModel: { type: String },
    llmFallbackAttemptedAt: { type: String },
    llmFallbackSucceededAt: { type: String },
    llmFallbackError: { type: String, select: false },
    llmModelUsed: { type: String },
    // Set when initial /generate accepted plain prose as narration because the model skipped JSON envelope
    dmInitialEnvelopeCoercedAt: { type: String },
    dmInitialEnvelopeCoercedChars: { type: Number },
    // Set when initial /generate recovered narration from truncated/invalid JSON (diagnostic)
    dmInitialEnvelopeSalvagedAt: { type: String },
    dmInitialEnvelopeSalvagedChars: { type: Number },
    // Last AI intent-router pass (play mode / combat declaration); select:false keeps load light
    intentRouterRaw: { type: String, select: false },
    intentRouterAt: { type: String },
    intentRouterError: { type: String, select: false },
    /** When set, MongoDB TTL deletes the doc at this time (draft character-only parties). Cleared when campaign exists or 2+ members. */
    draftPartyExpiresAt: {
        type: Date,
        default: null,
    },
});

GameStateSchema.index({ inviteToken: 1 }, { sparse: true });
GameStateSchema.index({ ownerUserId: 1 });
GameStateSchema.index({ memberUserIds: 1 });
GameStateSchema.index({ draftPartyExpiresAt: 1 }, { expireAfterSeconds: 0, sparse: true });

module.exports = mongoose.model('GameState', GameStateSchema);
