// GMAI/server/models/GameState.js

const mongoose = require('mongoose');


const GameStateSchema = new mongoose.Schema({
    gameId: {
        type: String,
        required: true,
    },
  
    gameSetup: Object,
    conversation: Array,
    summaryConversation: Array,
    summary: String,
    totalTokenCount: Number,
    userAndAssistantMessageCount: Number,
    systemMessageContentDM: String,
    // mode: exploration | combat | investigation | decision | initial
    mode: {
        type: String,
        default: 'exploration',
    },
    // Structured campaign specification generated by campaign generator
    campaignSpec: {
        type: Object,
    },
    // Raw last AI model output (for debugging / audit). Stored server-side only.
    rawModelOutput: {
        type: String,
        select: false,
    },
    // Consolidated system core message persisted once per game (DM-only)
    systemCore: {
        type: String,
        select: false,
    },
    // Raw last AI model REQUEST (system+user messages) for debugging. Stored server-side only.
    rawModelRequest: {
        type: String,
        select: false,
    },
    // LLM diagnostics and fallback metadata (timestamps and errors)
    llmCallEnteredAt: { type: String },
    llmCallStartedAt: { type: String },
    llmCallCompletedAt: { type: String },
    llmCallError: { type: String, select: false },
    llmCallFallbackAt: { type: String },
    llmFallbackModel: { type: String },
    llmFallbackAttemptedAt: { type: String },
    llmFallbackSucceededAt: { type: String },
    llmFallbackError: { type: String, select: false },
    llmModelUsed: { type: String },
});

module.exports = mongoose.model('GameState', GameStateSchema);
